### ISSUE TITLE
Visual Studio Express

### ISSUE THREAD

**Issue by Y-Less** [ctlajoie/DupSelection#10]
I'm using Visual Studio Express 2015 for Web, but can't install this extension.  Looking at the attached installer log it seems the express versions aren't supported, any chance of this being changed please?

```
13/04/2017 16:11:04 - Microsoft VSIX Installer
13/04/2017 16:11:04 - -------------------------------------------
13/04/2017 16:11:04 - Initializing Install...
13/04/2017 16:11:04 - Extension Details...
13/04/2017 16:11:04 - 	Identifier         : e5f7e157-f686-46b7-a588-85b08cdaa5f0
13/04/2017 16:11:04 - 	Name               : Duplicate Selection
13/04/2017 16:11:04 - 	Author             : Chris Lajoie
13/04/2017 16:11:04 - 	Version            : 2.0
13/04/2017 16:11:04 - 	Description        : Adds a command to duplicate the current selection (or line). Please see the More Info link for keybinding information.
13/04/2017 16:11:04 - 	Locale             : en-US
13/04/2017 16:11:04 - 	MoreInfoURL        : https://github.com/ctlajoie/DupSelection
13/04/2017 16:11:04 - 	InstalledByMSI     : False
13/04/2017 16:11:04 - 	SupportedFrameworkVersionRange : [4.0,)
13/04/2017 16:11:04 - 
13/04/2017 16:11:04 - 	SignatureState     : Unsigned
13/04/2017 16:11:04 - 	Supported Products : 
13/04/2017 16:11:04 - 		Microsoft.VisualStudio.Community
13/04/2017 16:11:04 - 			Version : [11.0,15.0]
13/04/2017 16:11:04 - 		Microsoft.VisualStudio.Pro
13/04/2017 16:11:04 - 			Version : [11.0,15.0]
13/04/2017 16:11:04 - 		Microsoft.VisualStudio.Enterprise
13/04/2017 16:11:04 - 			Version : [11.0,15.0]
13/04/2017 16:11:04 - 		Microsoft.VisualStudio.Premium
13/04/2017 16:11:04 - 			Version : [11.0,15.0]
13/04/2017 16:11:04 - 		Microsoft.VisualStudio.Ultimate
13/04/2017 16:11:04 - 			Version : [11.0,15.0]
13/04/2017 16:11:04 - 
13/04/2017 16:11:04 - 	References         : 
13/04/2017 16:11:04 - 		-------------------------------------------------------
13/04/2017 16:11:04 - 		Identifier   : Microsoft.VisualStudio.MPF.11.0
13/04/2017 16:11:04 - 		Name         : Visual Studio MPF 11.0
13/04/2017 16:11:04 - 		Version      : [11.0,12.0)
13/04/2017 16:11:04 - 		MoreInfoURL  : 
13/04/2017 16:11:04 - 		Nested       : No
13/04/2017 16:11:04 - 
13/04/2017 16:11:04 - Signature Details...
13/04/2017 16:11:04 - 	Extension is not signed.
13/04/2017 16:11:04 - 
13/04/2017 16:11:04 - Searching for applicable products...
13/04/2017 16:11:04 - Found installed product - Microsoft Visual Studio 2010 Ultimate
13/04/2017 16:11:04 - Found installed product - Microsoft Visual Studio Express 2015 for Web
13/04/2017 16:11:04 - Found installed product - Microsoft Visual Studio Express 2015 for Windows Desktop
13/04/2017 16:11:04 - Found installed product - Global Location
13/04/2017 16:11:04 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

(it lists I have 2010 Ultimate as well, but I'm less surprised it doesn't work there).

**Comment by ctlajoie** [comment]
The extension works on VS 2015 standard. I specified the widest support possible in the vsixmanifest file. If Microsoft doesn't allow it to be installed on VS Express for Web there's nothing I can do about it.
